name = "Tufte"
license = "MIT"
licenselink = "https://github.com/zacaytion/hugo-tufte/blob/master/LICENSE.md"
description = "A minimalist blog theme using Tufte-css."
homepage = "https://github.com/zacaytion/hugo-tufte"
tags = ["blog", "tufte", "minimal", 'light', "personal"]
features = ["math", "tufte-css", "tufte"]
min_version = 0.83

[author]
  name = "Zach Harris"
  homepage = "https://zharr.is"
