# Remove this if your site folder is not inside the theme folder
themesDir = "../../"

# Set your theme here
theme = "hugo-tufte"
# The language of your website (see https://www.andiamo.co.uk/resources/iso-language-codes/ for reference)
languageCode = "en-us"
# The url of your website
baseurl = "https://slashformotion.github.io/hugo-tufte/"
# The title of your website (shown on all the pages)
title = "Hugo-tufte Theme Example Site"
# Site wide kill switch for Latex support
math = true
# (If math is enabled) 
## if "katex" is set to true katex will be used to render LaTex, if not MathJax will be used instead
katex = true

pygmentsUseClasses = true
canonifyurls = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
